### ISSUE TITLE
endif syntax error on index.php 145

### ISSUE THREAD

**Issue by christisking** [lovetheidea/MoaDB#5]
Followed instructions to download and install, running centOS 6.4 with 
php-5.4.21-2.el6.remi.x86_64
php-pecl-mongo-1.6.0-1.el6.remi.5.4.x86_64

Getting error when I go to server/moaDB
Parse error: syntax error, unexpected 'endif' (T_ENDIF) in /var/www/html/moaDB/index.php on line 145

**Comment by FishTFM** [comment]
Same as you :/.
Tryed to fix the bug don't find where is the bug.

**Comment by lehins** [comment]
Same here.

**Comment by pessotti** [comment]
I have fixed this bug by changing all endif syntax to curly braces, get the code here: http://pastebin.com/7TyWYN0Q

**Comment by trentramseyer** [comment]
It is not the endif/curly braces issue. It is an issue with your server is set to require "<?php"  when starting php code.   Some of the lines only have "<?"

**Comment by alikayhan** [comment]
Set "short_open_tag = On" in your php.ini file. This has solved my problem.

**Comment by lovetheidea** [comment]
Change <?'s to <?php
